music/urls.py
from django.conf.urls import url
from music import views




app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^blog/$', views.blog, name='blog'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^resume/$', views.resume, name='resume'),

]

website/urls.py
from django.contrib import admin
from django.conf.urls import url, include



urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^', include('music.urls')),
]

about/models.py
from django.db import models

# Create your models here.

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.

music/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models import Model
from django.utils import timezone


class Post(models.Model):
    post_title = models.CharField(max_length=250)
    post_description = models.TextField()
    post_author = models.ForeignKey(User, default=1)
    post_image = models.URLField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'post'

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.post_title

Resume/views.py
from django.shortcuts import render

# Create your views here.

about/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

gallery/views.py
from django.shortcuts import render

# Create your views here.

music/views.py
import logging

from music.models import Post

logger = logging.getLogger(__name__)

from django.shortcuts import render





def index(request):
    logger.info('what is this', request)
    return render(request, 'index.html', {'title': 'Welcome to HomePage - Vasu Thopuri'})


def about(request):
    print("request is", request)

    return render(request, 'about.html', {'title': 'About - Vasu Thopuri'})


def blog(request):
     posts = Post.objects.all()
     return render(request, 'blog.html', {'title': 'blog - Vasu thopuri', 'posts': posts})


def gallery(request):
    print("request is", request)

    return render(request, 'gallery.html', {'title': 'gallery - Vasu Thopuri'})

def resume(request):
    print("request is", request)

    return render(request, 'resume.html', {'title': 'resume - Vasu Thopuri'})

def contact(request):
    print("request is", request)

    return render(request, 'contact.html', {'title': 'Contact - Vasu Thopuri'})

templates/Resume.html
{% extends "base.html" %}
{% block title %} {{ title }} {% endblock %}
{% block body %}
    <h2>it will update soon </h2>
{% endblock %}

templates/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} {{ title }} {% endblock %}
{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="fb-profile">
                <img align="left" class="fb-image-lg" src="{% static 'music/image/abd.jpg' %}"
                     alt="Profile image example"/>
                <img align="left" class="fb-image-profile thumbnail" src="{% static 'music/image/abd2.jpg' %}"
                     alt="Profile image example"/>
                <div class="fb-profile-text">
                    <h1>Vasu Thopuri</h1>

                </div>
            </div>
        </div>
    </div> <!-- /container fluid-->
    <div class="container">
        <div class="col-sm-8">

            <div data-spy="scroll" class="tabbable-panel">
                <div class="tabbable-line">
                    <ul class="nav nav-tabs ">
                        <li class="active">
                            <a href="#profile_tab" data-toggle="tab">
                                Profile </a>
                        </li>
                        <li>
                            <a href="#edu_and_career_tab" data-toggle="tab">
                                Education & Career</a>
                        </li>
                        <li>
                            <a href="#tech_stack_tab" data-toggle="tab">
                                Tech Stack</a>
                        </li>
                        <li>
                            <a href="#influencers_tab" data-toggle="tab">
                                Influencers</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="profile_tab">
                            <p>
                                I am vasu thopuri graduated in <b> 2017 </b> in department of Electronics and Communication Engineering
                                with <b> 70%</b>.i am searching for a job , i have knowledge on python and django framework and Linux also.

                            </p>
                            <h5>Languages</h5>
                            <p>
                                Telugu&nbsp;,English&nbsp;
                            </p>
                            <h5>Education </h5>
                            <p>I have done B.Tech in Electronics And Communication Engineering</p>
                        </div>
                        <div class="tab-pane" id="edu_and_career_tab">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <h5>Graduation</h5>
                                        <p> B.Tech</p>
                                    </div>
                                    <div class="form-group">
                                        <h5>Intermediate(+2)</h5>
                                        <p>Maths,Physics,Chemistry</p>
                                    </div>
                                    <div class="form-group">
                                        <h5>Schoolings</h5>
                                        <p>SSC</p>
                                    </div>

                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <h5>Prakasam Engineering College</h5>
                                        <p> Kandukur,A.P</p>
                                    </div>
                                    <div class="form-group">
                                        <h5>Sri Prathibha Jr.Collge</h5>
                                        <p>Ongole,A.P</p>
                                    </div>
                                    <div class="form-group">
                                        <h5>Lakshmi High School</h5>
                                        <p> Addanki,A.P</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="tech_stack_tab">

                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <h5>UI</h5>
                                        <p> Bootstrap</p>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <h5>Web Frameworks</h5>
                                        <p> Django</p>
                                    </div>
                                    <div class="form-group">
                                        <h5>Languages Known</h5>
                                        <p> Python,C</p>
                                    </div>

                                </div>

                            </div>
                        </div>
                        <div class="tab-pane" id="influencers_tab">
                            <div class="row">
                                <div class="col-sm-12 ">
                                    <div class="media">
                                        <div class="media-left">
                                            <a href="#">
                                                <img class="img-circle influencer-logo"
                                                     src="{% static 'music/image/hitler.jpg' %}" alt="...">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading">Adlof Hitler</h4>
                                            <h5>Make the lie big, make it simple, keep saying it, and eventually they will believe it.</h5>
                                            <p>It is always more difficult to fight against faith than against knowledge.</p>
                                        </div>
                                    </div>

                                    <div class="media">
                                        <div class="media-left">
                                            <a href="#">
                                                <img class="img-circle influencer-logo"
                                                     src="{% static 'music/image/stalin.jpg' %}" alt="...">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading">Josef Stalin</h4>
                                            <h5>Death is the solution to all problems. No man - no problem.</h5>
                                            <p>I trust no one, not even myself.</p>
                                            <p></p>
                                        </div>
                                    </div>

                                    <div class="media">
                                        <div class="media-left">
                                            <a href="#">
                                                <img class="img-circle influencer-logo"
                                                     src="{% static 'music/image/charli.jpg' %}" alt="...">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading">Charlie Chaplin</h4>
                                            <h5>We think too much and feel too little.</h5>
                                            <h5>Life could be wonderful if people would leave you alone.</h5>
                                        </div>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="menu_title">
                    Get in touch
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">


                            <div class="form-group ">
                                <span>                                    <a
                                        href=https://www.facebook.com/vasu.thopuri.7 class="fb" target="_blank">
                                    <i class="fa fa-facebook"></i></a>
                                </span>
                                <span>
                                    <a href=https://www.linkedin.com/in/vasu-thopuri-7822ab136/ class="linkedin" target="_blank">
                                        <i class="fa fa-linkedin"></i></a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'music/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'music/css/bootstrap-custom-style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'music/css/styles.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'music/image/abd.jpg' %}"/>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <script src="{% static 'music/js/jquery.min.js' %}"></script>
    <script src="{% static 'music/js/bootstrap.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>


</head>

    <body>
    {% include 'header.html' %}

{% block body %}
{% endblock %}
    </body>
</html>

templates/blog.html
{% extends "base.html" %}
{% block title %} {{ title }} {% endblock %}
{% block body %}
    <section id="blog">
        <div class="container">

            <div class="row">
                <div class="col-lg-6 col-lg-offset-3 text-center">
                    <h2><span class="ion-minus"></span>Blog Posts<span class="ion-minus"></span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
                        Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
                        ridiculus </p><br>
                </div>
            </div>

            <div class="row">

                <div id="slider" class="carousel slide" data-ride="carousel">

                    <ol class="carousel-indicators">
                        <li data-target="#slider" data-slide-to="0" class="active"></li>
                        <li data-target="#slider" data-slide-to="1"></li>
                    </ol>


                    <!-- Carousel items -->
                    <div class="carousel-inner">

                        <div class="item active">
                            <div class="row">
                                {% if posts %}
                                    {% for post in posts %}
                                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                            <div class="card text-center">
                                                <img class="card-img-top"
                                                     src={{ post.post_image }}
                                                             alt="" width="100%">
                                                <div class="card-block">
                                                    <h4 class="card-title">{{ post.post_title }}</h4>
                                                    <p class="card-text">{{ post.post_description|truncatechars:200 }}</p>
                                                    <a class="btn btn-default" href="#">Read More</a>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}

                                {% endif %}


                            </div> <!-- row -->
                        </div> <!-- item -->


                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% block title %} {{ title }} {% endblock %}
{% block body %}
    <h2>Hello This is MY Mail Id </h2>
    <a href="mailto:vasuthopuri333@gmail.com">Click Here Email to me</a>.<br>
{% endblock %}

templates/gallery.html
 {% extends "base.html" %}
{% block title %} {{ title }} {% endblock %}
{% block body %}
    <h2>Hello</h2>
{% endblock %}

templates/header.html
{% load staticfiles %}
<nav class="navbar navbar-default" role="navigation">
    	  <div class="container">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
                <a href="{% url 'music:index' %}" class="navbar-brand">vasu thopuri</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="navbar-brand-centered">
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="{% url 'music:about' %}">about</a></li>
		        <li><a href="{% url 'music:blog' %}">blog</a></li>
		        <li><a href="{% url 'music:gallery' %}">gallery</a></li>
		        <li><a href="{% url 'music:resume' %}">resume</a></li>
                <li><a href="{% url 'music:contact' %}">contact</a></li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
   </nav>

templates/index.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block body %}
    <div class="carousel fade-carousel slide carousel-fade" data-ride="carousel" data-interval="4000" id="bs-carousel">
        <!-- Overlay -->

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#bs-carousel" data-slide-to="1"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item slides active">
                <div class="slide-1">
                    <div class="overlay"></div>
                </div>
                <div class="hero">
                    <h>
                        <h1>I'm Vasu Thopuri</h1>
                        <h3>Welcome to my Home</h3>
                    </h>
                </div>
            </div>
            <div class="item slides">
                <div class="slide-2">
                    <div class="overlay"></div>
                </div>
                <div class="hero">
                    <h>
                        <h1>Dreamer</h1>
                        <h3>Haven't seen my profile yet ..?</h3>
                    </h>
                </div>
            </div>

        </div>
    </div>
{% endblock %}